// name
// breed
// gender
// color1
// gene1
// color2
// gene2
// color3
// gene3

let fakeDragons = [
	{
		idx: "",
		frid: 72858568,
		name: "Asclepias",
		img: "",
		gender: "Male",
		breed: "Fae",
		goalpair: "",
		goalline: "",
		colordist: "",
		matename: "",
		"": "",
		status: "",
		acceptablerange: "",
		source: "Lair",
		parents: "Hibiscus/Viridian",
		pricolor: "Jungle",
		prigene: "Leopard",
		seccolor: "Sky",
		secgene: "Noxtide",
		tercolor: "Peridot",
		tergene: "Underbelly",
		pricolornum: 80,
		seccolornum: 55,
		tercolornum: 94,
		prigenetier: 2,
		secgenetier: 3,
		tergenetier: 2,
		breedtier: 1,
		clutchid: 728586,
		level: 1,
		flight: "Nature",
		eyetype: "Uncommon",
		url: "https://www1.flightrising.com/dragon/72858568",
		portraiturl:
			"https://www1.flightrising.com/rendern/portraits/728586/72858568p.png",
		bigpicurl:
			"https://www1.flightrising.com/rendern/350/728586/72858568_350.png",
		minipicurl:
			"https://www1.flightrising.com/rendern/avatars/728586/72858568.png",
		fathername: "Hibiscus",
		fatherid: 67705765,
		mothername: "Viridian",
		motherid: 68061516,
		hatchday: "6-Oct-21",
		pridist: "",
		secdist: "",
		terdist: "",
	},
	{
		idx: "",
		frid: 72858569,
		name: "Amrita",
		img: "",
		gender: "Female",
		breed: "Fae",
		goalpair: "",
		goalline: "",
		colordist: "",
		matename: "",
		"": "",
		status: "",
		acceptablerange: "",
		source: "Lair",
		parents: "Hibiscus/Viridian",
		pricolor: "Jungle",
		prigene: "Leopard",
		seccolor: "Gloom",
		secgene: "Noxtide",
		tercolor: "Moss",
		tergene: "Underbelly",
		pricolornum: 80,
		seccolornum: 13,
		tercolornum: 100,
		prigenetier: 2,
		secgenetier: 3,
		tergenetier: 2,
		breedtier: 1,
		clutchid: 728586,
		level: 1,
		flight: "Nature",
		eyetype: "Unusual",
		url: "https://www1.flightrising.com/dragon/72858569",
		portraiturl:
			"https://www1.flightrising.com/rendern/portraits/728586/72858569p.png",
		bigpicurl:
			"https://www1.flightrising.com/rendern/350/728586/72858569_350.png",
		minipicurl:
			"https://www1.flightrising.com/rendern/avatars/728586/72858569.png",
		fathername: "Hibiscus",
		fatherid: 67705765,
		mothername: "Viridian",
		motherid: 68061516,
		hatchday: "6-Oct-21",
		pridist: "",
		secdist: "",
		terdist: "",
	},
	{
		idx: "",
		frid: 72858575,
		name: "Hazel",
		img: "",
		gender: "Female",
		breed: "Coatl",
		goalpair: "",
		goalline: "",
		colordist: "",
		matename: "",
		"": "",
		status: "",
		acceptablerange: "",
		source: "Lair",
		parents: "Amet/Bushwillow",
		pricolor: "Brown",
		prigene: "Cherub",
		seccolor: "Forest",
		secgene: "Freckle",
		tercolor: "Forest",
		tergene: "Underbelly",
		pricolornum: 145,
		seccolornum: 82,
		tercolornum: 82,
		prigenetier: 3,
		secgenetier: 2,
		tergenetier: 2,
		breedtier: 5,
		clutchid: 728586,
		level: 1,
		flight: "Nature",
		eyetype: "Pastel",
		url: "https://www1.flightrising.com/dragon/72858575",
		portraiturl:
			"https://www1.flightrising.com/rendern/portraits/728586/72858575p.png",
		bigpicurl:
			"https://www1.flightrising.com/rendern/350/728586/72858575_350.png",
		minipicurl:
			"https://www1.flightrising.com/rendern/avatars/728586/72858575.png",
		fathername: "Amet",
		fatherid: 29629304,
		mothername: "Bushwillow",
		motherid: 30935086,
		hatchday: "6-Oct-21",
		pridist: "",
		secdist: "",
		terdist: "",
	},
	{
		idx: "",
		frid: 72858576,
		name: "Spruce",
		img: "",
		gender: "Male",
		breed: "Coatl",
		goalpair: "",
		goalline: "",
		colordist: "",
		matename: "",
		"": "",
		status: "",
		acceptablerange: "",
		source: "Lair",
		parents: "Amet/Bushwillow",
		pricolor: "Tarnish",
		prigene: "Ripple",
		seccolor: "Hunter",
		secgene: "Freckle",
		tercolor: "Hunter",
		tergene: "Underbelly",
		pricolornum: 143,
		seccolornum: 81,
		tercolornum: 81,
		prigenetier: 3,
		secgenetier: 2,
		tergenetier: 2,
		breedtier: 5,
		clutchid: 728586,
		level: 1,
		flight: "Nature",
		eyetype: "Common",
		url: "https://www1.flightrising.com/dragon/72858576",
		portraiturl:
			"https://www1.flightrising.com/rendern/portraits/728586/72858576p.png",
		bigpicurl:
			"https://www1.flightrising.com/rendern/350/728586/72858576_350.png",
		minipicurl:
			"https://www1.flightrising.com/rendern/avatars/728586/72858576.png",
		fathername: "Amet",
		fatherid: 29629304,
		mothername: "Bushwillow",
		motherid: 30935086,
		hatchday: "6-Oct-21",
		pridist: "",
		secdist: "",
		terdist: "",
	},
	{
		idx: "",
		frid: 72858591,
		name: "Cycas",
		img: "",
		gender: "Male",
		breed: "Fae",
		goalpair: "",
		goalline: "",
		colordist: "",
		matename: "",
		"": "",
		status: "",
		acceptablerange: "",
		source: "Lair",
		parents: "Strelitzia/Datura",
		pricolor: "Abyss",
		prigene: "Cherub",
		seccolor: "Radioactive",
		secgene: "Trail",
		tercolor: "Fuchsia",
		tergene: "Capsule",
		pricolornum: 60,
		seccolornum: 92,
		tercolornum: 170,
		prigenetier: 3,
		secgenetier: 4,
		tergenetier: 4,
		breedtier: 1,
		clutchid: 728586,
		level: 1,
		flight: "Nature",
		eyetype: "Unusual",
		url: "https://www1.flightrising.com/dragon/72858591",
		portraiturl:
			"https://www1.flightrising.com/rendern/portraits/728586/72858591p.png",
		bigpicurl:
			"https://www1.flightrising.com/rendern/350/728586/72858591_350.png",
		minipicurl:
			"https://www1.flightrising.com/rendern/avatars/728586/72858591.png",
		fathername: "Strelitzia",
		fatherid: 43332599,
		mothername: "Datura",
		motherid: 43332946,
		hatchday: "6-Oct-21",
		pridist: "",
		secdist: "",
		terdist: "",
	},
	{
		idx: "",
		frid: 72858592,
		name: "Dianthus",
		img: "",
		gender: "Male",
		breed: "Pearlcatcher",
		goalpair: "",
		goalline: "",
		colordist: "",
		matename: "",
		"": "",
		status: "",
		acceptablerange: "",
		source: "Lair",
		parents: "Strelitzia/Datura",
		pricolor: "Abyss",
		prigene: "Cherub",
		seccolor: "Radioactive",
		secgene: "Trail",
		tercolor: "Fuchsia",
		tergene: "Capsule",
		pricolornum: 60,
		seccolornum: 92,
		tercolornum: 170,
		prigenetier: 3,
		secgenetier: 4,
		tergenetier: 4,
		breedtier: 2,
		clutchid: 728586,
		level: 1,
		flight: "Nature",
		eyetype: "Unusual",
		url: "https://www1.flightrising.com/dragon/72858592",
		portraiturl:
			"https://www1.flightrising.com/rendern/portraits/728586/72858592p.png",
		bigpicurl:
			"https://www1.flightrising.com/rendern/350/728586/72858592_350.png",
		minipicurl:
			"https://www1.flightrising.com/rendern/avatars/728586/72858592.png",
		fathername: "Strelitzia",
		fatherid: 43332599,
		mothername: "Datura",
		motherid: 43332946,
		hatchday: "6-Oct-21",
		pridist: "",
		secdist: "",
		terdist: "",
	},
	{
		idx: "",
		frid: 72876163,
		name: "Camassia",
		img: "",
		gender: "Female",
		breed: "Gaoler",
		goalpair: "",
		goalline: "",
		colordist: "",
		matename: "",
		"": "",
		status: "",
		acceptablerange: "",
		source: "Lair",
		parents: "Aspen/Sequoia",
		pricolor: "Umber",
		prigene: "Giraffe",
		seccolor: "Camo",
		secgene: "Peregrine",
		tercolor: "Mist",
		tergene: "Blossom",
		pricolornum: 140,
		seccolornum: 83,
		tercolornum: 31,
		prigenetier: 3,
		secgenetier: 2,
		tergenetier: 5,
		breedtier: 6,
		clutchid: 728762,
		level: 1,
		flight: "Nature",
		eyetype: "Unusual",
		url: "https://www1.flightrising.com/dragon/72876163",
		portraiturl:
			"https://www1.flightrising.com/rendern/portraits/728762/72876163p.png",
		bigpicurl:
			"https://www1.flightrising.com/rendern/350/728762/72876163_350.png",
		minipicurl:
			"https://www1.flightrising.com/rendern/avatars/728762/72876163.png",
		fathername: "Aspen",
		fatherid: 67418073,
		mothername: "Sequoia",
		motherid: 67186884,
		hatchday: "7-Oct-21",
		pridist: "",
		secdist: "",
		terdist: "",
	},
	{
		idx: "",
		frid: 72876164,
		name: "Flax",
		img: "",
		gender: "Male",
		breed: "Gaoler",
		goalpair: "",
		goalline: "",
		colordist: "",
		matename: "",
		"": "",
		status: "",
		acceptablerange: "",
		source: "Lair",
		parents: "Aspen/Sequoia",
		pricolor: "Sable",
		prigene: "Ripple",
		seccolor: "Hunter",
		secgene: "Peregrine",
		tercolor: "Splash",
		tergene: "Blossom",
		pricolornum: 139,
		seccolornum: 81,
		tercolornum: 53,
		prigenetier: 3,
		secgenetier: 2,
		tergenetier: 5,
		breedtier: 6,
		clutchid: 728762,
		level: 1,
		flight: "Nature",
		eyetype: "Uncommon",
		url: "https://www1.flightrising.com/dragon/72876164",
		portraiturl:
			"https://www1.flightrising.com/rendern/portraits/728762/72876164p.png",
		bigpicurl:
			"https://www1.flightrising.com/rendern/350/728762/72876164_350.png",
		minipicurl:
			"https://www1.flightrising.com/rendern/avatars/728762/72876164.png",
		fathername: "Aspen",
		fatherid: 67418073,
		mothername: "Sequoia",
		motherid: 67186884,
		hatchday: "7-Oct-21",
		pridist: "",
		secdist: "",
		terdist: "",
	},
	{
		idx: "",
		frid: 72876165,
		name: "Aquilegia",
		img: "",
		gender: "Male",
		breed: "Gaoler",
		goalpair: "",
		goalline: "",
		colordist: "",
		matename: "",
		"": "",
		status: "",
		acceptablerange: "",
		source: "Lair",
		parents: "Aspen/Sequoia",
		pricolor: "Umber",
		prigene: "Ripple",
		seccolor: "Spruce",
		secgene: "Peregrine",
		tercolor: "Cobalt",
		tergene: "Blossom",
		pricolornum: 140,
		seccolornum: 70,
		tercolornum: 48,
		prigenetier: 3,
		secgenetier: 2,
		tergenetier: 5,
		breedtier: 6,
		clutchid: 728762,
		level: 1,
		flight: "Nature",
		eyetype: "Rare",
		url: "https://www1.flightrising.com/dragon/72876165",
		portraiturl:
			"https://www1.flightrising.com/rendern/portraits/728762/72876165p.png",
		bigpicurl:
			"https://www1.flightrising.com/rendern/350/728762/72876165_350.png",
		minipicurl:
			"https://www1.flightrising.com/rendern/avatars/728762/72876165.png",
		fathername: "Aspen",
		fatherid: 67418073,
		mothername: "Sequoia",
		motherid: 67186884,
		hatchday: "7-Oct-21",
		pridist: "",
		secdist: "",
		terdist: "",
	},
	{
		idx: "",
		frid: 72858572,
		name: "Ashlin",
		img: "",
		gender: "Female",
		breed: "Skydancer",
		goalpair: "",
		goalline: "",
		colordist: "",
		matename: "",
		"": "",
		status: "",
		acceptablerange: "",
		source: "Lair",
		parents: "Faerie/Ivette",
		pricolor: "Jade",
		prigene: "Wasp",
		seccolor: "Seafoam",
		secgene: "Shimmer",
		tercolor: "Green",
		tergene: "Filigree",
		pricolornum: 74,
		seccolornum: 72,
		tercolornum: 87,
		prigenetier: 5,
		secgenetier: 5,
		tergenetier: 5,
		breedtier: 3,
		clutchid: 728586,
		level: 1,
		flight: "Nature",
		eyetype: "Uncommon",
		url: "https://www1.flightrising.com/dragon/72858572",
		portraiturl:
			"https://www1.flightrising.com/rendern/portraits/728586/72858572p.png",
		bigpicurl:
			"https://www1.flightrising.com/rendern/350/728586/72858572_350.png",
		minipicurl:
			"https://www1.flightrising.com/rendern/avatars/728586/72858572.png",
		fathername: "Faerie",
		fatherid: 63655005,
		mothername: "Ivette",
		motherid: 67285281,
		hatchday: "6-Oct-21",
		pridist: "",
		secdist: "",
		terdist: "",
	},
	{
		idx: "",
		frid: 72858573,
		name: "Aibreanne",
		img: "",
		gender: "Female",
		breed: "Spiral",
		goalpair: "",
		goalline: "",
		colordist: "",
		matename: "",
		"": "",
		status: "",
		acceptablerange: "",
		source: "Lair",
		parents: "Faerie/Ivette",
		pricolor: "Seafoam",
		prigene: "Wasp",
		seccolor: "Spruce",
		secgene: "Shimmer",
		tercolor: "Green",
		tergene: "Glimmer",
		pricolornum: 72,
		seccolornum: 70,
		tercolornum: 87,
		prigenetier: 5,
		secgenetier: 5,
		tergenetier: 5,
		breedtier: 2,
		clutchid: 728586,
		level: 1,
		flight: "Nature",
		eyetype: "Bright",
		url: "https://www1.flightrising.com/dragon/72858573",
		portraiturl:
			"https://www1.flightrising.com/rendern/portraits/728586/72858573p.png",
		bigpicurl:
			"https://www1.flightrising.com/rendern/350/728586/72858573_350.png",
		minipicurl:
			"https://www1.flightrising.com/rendern/avatars/728586/72858573.png",
		fathername: "Faerie",
		fatherid: 63655005,
		mothername: "Ivette",
		motherid: 67285281,
		hatchday: "6-Oct-21",
		pridist: "",
		secdist: "",
		terdist: "",
	},
	{
		idx: "",
		frid: 72858574,
		name: "Mistvale",
		img: "",
		gender: "Female",
		breed: "Skydancer",
		goalpair: "",
		goalline: "",
		colordist: "",
		matename: "",
		"": "",
		status: "",
		acceptablerange: "",
		source: "Lair",
		parents: "Faerie/Ivette",
		pricolor: "Mint",
		prigene: "Iridescent",
		seccolor: "Spruce",
		secgene: "Bee",
		tercolor: "Green",
		tergene: "Glimmer",
		pricolornum: 73,
		seccolornum: 70,
		tercolornum: 87,
		prigenetier: 5,
		secgenetier: 5,
		tergenetier: 5,
		breedtier: 3,
		clutchid: 728586,
		level: 1,
		flight: "Nature",
		eyetype: "Rare",
		url: "https://www1.flightrising.com/dragon/72858574",
		portraiturl:
			"https://www1.flightrising.com/rendern/portraits/728586/72858574p.png",
		bigpicurl:
			"https://www1.flightrising.com/rendern/350/728586/72858574_350.png",
		minipicurl:
			"https://www1.flightrising.com/rendern/avatars/728586/72858574.png",
		fathername: "Faerie",
		fatherid: 63655005,
		mothername: "Ivette",
		motherid: 67285281,
		hatchday: "6-Oct-21",
		pridist: "",
		secdist: "",
		terdist: "",
	},
];

export { fakeDragons };
